# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnalysisResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeAnswer", llm_response=llm_response, mode="request")
        return typing.cast(types.AnalysisResponse, __result__)

    def ExtractProjects(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Project"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProjects", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.Project"], __result__)

    def FinalAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FinalAnalysis", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def GenerateQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.QuestionResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateQuestion", llm_response=llm_response, mode="request")
        return typing.cast(types.QuestionResponse, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnalysisResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeAnswer", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnalysisResponse, __result__)

    def ExtractProjects(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.Project"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProjects", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.Project"], __result__)

    def FinalAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FinalAnalysis", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def GenerateQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.QuestionResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.QuestionResponse, __result__)

    