# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class AnalysisResponse(BaseModel):
    analysis: typing.Optional["AnswerAnalysis"] = None
    decision: typing.Optional["InterviewDecision"] = None
    pastContext: typing.Optional["ProjectPastContext"] = None

class AnswerAnalysis(BaseModel):
    clarity: typing.Optional[int] = None
    correctness: typing.Optional[int] = None
    depth: typing.Optional[int] = None
    review: typing.Optional[str] = None
    uncovered_gaps: typing.List[str]

class InterviewDecision(BaseModel):
    intent: typing.Optional[types.Intent] = None
    urgency: typing.Optional[float] = None
    confidence: typing.Optional[float] = None
    rationale: typing.Optional[str] = None

class InterviewState(BaseModel):
    stage: typing.Optional[types.InterviewStage] = None
    turn_index: typing.Optional[int] = None
    max_turns: typing.Optional[int] = None
    max_followups_per_question: typing.Optional[int] = None
    max_questions_per_project: typing.Optional[int] = None
    projects_done: typing.Dict[str, bool]
    active_project_id: typing.Optional[str] = None
    active_question_id: typing.Optional[str] = None
    projects: typing.Dict[str, "ProjectState"]
    decision: typing.Optional["InterviewDecision"] = None
    last_answer: typing.Optional[str] = None

class Project(BaseModel):
    name: typing.Optional[str] = None
    description: typing.List[str]
    tech_stack: typing.List[str]
    role: typing.Optional[str] = None
    complexity: typing.Optional[int] = None

class ProjectPastContext(BaseModel):
    weak_areas: typing.List[str]
    strong_areas: typing.List[str]
    unanswered_concepts: typing.List[str]
    coverage_score: typing.Optional[float] = None

class ProjectState(BaseModel):
    name: typing.Optional[str] = None
    description: typing.List[str]
    claimed_stack: typing.List[str]
    complexity: typing.Optional[int] = None
    question_ids: typing.Dict[str, str]
    followup_count: typing.Dict[str, int]
    parent_questions: typing.Dict[str, str]
    per_question_answer_analysis: typing.Optional[typing.Dict[str, "AnswerAnalysis"]] = None
    overall_analysis: typing.Optional["ProjectPastContext"] = None

class QuestionResponse(BaseModel):
    question: typing.Optional[str] = None
    question_id: typing.Optional[str] = None
    parent_question_id: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
