# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def AnalyzeAnswer(self, question: str,answer: str,state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> types.AnalysisResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AnalyzeAnswer(question=question,answer=answer,state=state,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeAnswer", args={
                "question": question,"answer": answer,"state": state,
            })
            return typing.cast(types.AnalysisResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractProjects(self, resume_text: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Project"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractProjects(resume_text=resume_text,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractProjects", args={
                "resume_text": resume_text,
            })
            return typing.cast(typing.List["types.Project"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def FinalAnalysis(self, state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.FinalAnalysis(state=state,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="FinalAnalysis", args={
                "state": state,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateQuestion(self, state: types.InterviewState,intent: types.Intent,urgency: float,
        baml_options: BamlCallOptions = {},
    ) -> types.QuestionResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GenerateQuestion(state=state,intent=intent,urgency=urgency,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateQuestion", args={
                "state": state,"intent": intent,"urgency": urgency,
            })
            return typing.cast(types.QuestionResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAnswer(self, question: str,answer: str,state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AnalysisResponse, types.AnalysisResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeAnswer", args={
            "question": question,"answer": answer,"state": state,
        })
        return baml_py.BamlSyncStream[stream_types.AnalysisResponse, types.AnalysisResponse](
          __result__,
          lambda x: typing.cast(stream_types.AnalysisResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AnalysisResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractProjects(self, resume_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.Project"], typing.List["types.Project"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractProjects", args={
            "resume_text": resume_text,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.Project"], typing.List["types.Project"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.Project"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.Project"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def FinalAnalysis(self, state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="FinalAnalysis", args={
            "state": state,
        })
        return baml_py.BamlSyncStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateQuestion(self, state: types.InterviewState,intent: types.Intent,urgency: float,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.QuestionResponse, types.QuestionResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateQuestion", args={
            "state": state,"intent": intent,"urgency": urgency,
        })
        return baml_py.BamlSyncStream[stream_types.QuestionResponse, types.QuestionResponse](
          __result__,
          lambda x: typing.cast(stream_types.QuestionResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QuestionResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAnswer(self, question: str,answer: str,state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeAnswer", args={
            "question": question,"answer": answer,"state": state,
        }, mode="request")
        return __result__
    def ExtractProjects(self, resume_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProjects", args={
            "resume_text": resume_text,
        }, mode="request")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    def FinalAnalysis(self, state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FinalAnalysis", args={
            "state": state,
        }, mode="request")
        return __result__
    def GenerateQuestion(self, state: types.InterviewState,intent: types.Intent,urgency: float,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateQuestion", args={
            "state": state,"intent": intent,"urgency": urgency,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeAnswer(self, question: str,answer: str,state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeAnswer", args={
            "question": question,"answer": answer,"state": state,
        }, mode="stream")
        return __result__
    def ExtractProjects(self, resume_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProjects", args={
            "resume_text": resume_text,
        }, mode="stream")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    def FinalAnalysis(self, state: types.InterviewState,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FinalAnalysis", args={
            "state": state,
        }, mode="stream")
        return __result__
    def GenerateQuestion(self, state: types.InterviewState,intent: types.Intent,urgency: float,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateQuestion", args={
            "state": state,"intent": intent,"urgency": urgency,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))