# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class Intent(str, Enum):
    ProbeDepth = "ProbeDepth"
    FollowUp = "FollowUp"
    Clarify = "Clarify"
    Challenge = "Challenge"
    MoveOn = "MoveOn"
    SwitchProject = "SwitchProject"
    WrapUp = "WrapUp"

class InterviewStage(str, Enum):
    Intro = "Intro"
    DeepDive = "DeepDive"
    FollowUp = "FollowUp"
    WrapUp = "WrapUp"

# #########################################################################
# Generated classes (8)
# #########################################################################

class AnalysisResponse(BaseModel):
    analysis: "AnswerAnalysis"
    decision: "InterviewDecision"
    pastContext: "ProjectPastContext"

class AnswerAnalysis(BaseModel):
    clarity: int
    correctness: int
    depth: int
    review: str
    uncovered_gaps: typing.List[str]

class InterviewDecision(BaseModel):
    intent: Intent
    urgency: float
    confidence: float
    rationale: str

class InterviewState(BaseModel):
    stage: InterviewStage
    turn_index: int
    max_turns: int
    max_followups_per_question: int
    max_questions_per_project: int
    projects_done: typing.Dict[str, bool]
    active_project_id: typing.Optional[str] = None
    active_question_id: typing.Optional[str] = None
    projects: typing.Dict[str, "ProjectState"]
    decision: "InterviewDecision"
    last_answer: typing.Optional[str] = None

class Project(BaseModel):
    name: str
    description: typing.List[str]
    tech_stack: typing.List[str]
    role: str
    complexity: int

class ProjectPastContext(BaseModel):
    weak_areas: typing.List[str]
    strong_areas: typing.List[str]
    unanswered_concepts: typing.List[str]
    coverage_score: float

class ProjectState(BaseModel):
    name: str
    description: typing.List[str]
    claimed_stack: typing.List[str]
    complexity: int
    question_ids: typing.Dict[str, str]
    followup_count: typing.Dict[str, int]
    parent_questions: typing.Dict[str, str]
    per_question_answer_analysis: typing.Optional[typing.Dict[str, "AnswerAnalysis"]] = None
    overall_analysis: "ProjectPastContext"

class QuestionResponse(BaseModel):
    question: str
    question_id: str
    parent_question_id: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
