# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnalysisResponse": types.AnalysisResponse,
    "stream_types.AnalysisResponse": stream_types.AnalysisResponse,

    "types.AnswerAnalysis": types.AnswerAnalysis,
    "stream_types.AnswerAnalysis": stream_types.AnswerAnalysis,

    "types.InterviewDecision": types.InterviewDecision,
    "stream_types.InterviewDecision": stream_types.InterviewDecision,

    "types.InterviewState": types.InterviewState,
    "stream_types.InterviewState": stream_types.InterviewState,

    "types.Project": types.Project,
    "stream_types.Project": stream_types.Project,

    "types.ProjectPastContext": types.ProjectPastContext,
    "stream_types.ProjectPastContext": stream_types.ProjectPastContext,

    "types.ProjectState": types.ProjectState,
    "stream_types.ProjectState": stream_types.ProjectState,

    "types.QuestionResponse": types.QuestionResponse,
    "stream_types.QuestionResponse": stream_types.QuestionResponse,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,


    "types.Intent": types.Intent,

    "types.InterviewStage": types.InterviewStage,

}